server:
  port: 8889
spring:
  application:
    name: augustczar-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/augustczar/augustczar-erudio-config-server
# Utilizar para repositorio privado caso queira
          #username: username
          #password: password
          default-label: main
          search-paths:
          - 'greeting-service*'